---
title: "Module1.3 - random stuff"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R working with probability distributions
```{r random values from uniform}
# uniform
runif(1)

runif(10)

runif(10,min=-5,max=7)

# coin flip
runif(20)<0.5
rbinom(10,8,0.5)
```

```{r}
runif(10) # using defaults for max,min
rnorm(10) # using defaults
rnorm(10,mean=5,sd=3) # mu,sig
rpois(10,1) # lambda
rbinom(10,5,0.2) #n,p
```

```{r distribution properties}

rnorm(1, mean = 0, sd = 1) # as before....

dnorm(2.3, mean = 0, sd = 1) # will returm probability (or density) for a value given parameters
pnorm(1.7) # cumulative probability
qnorm(0.7) # value for that quantile
qnorm(1.7)  # what will happen here? 

# same for all distributions
dpois(4, 1)
ppois(4, 1)
qpois(0.95,1)


```


```{r sampling}
s = cars$speed; 
sample(s) # will sample without replacement same size of data, i.e. will just permute
sample(s,replace=TRUE) # same but with replacement, i.e. resampling for bootstrap
sample(s,replace=TRUE,size=100) # same but you say how many samples
#sample(s,1000) # What will happen here? 
```

